// Generated by create-api-home — live runmoa Storefront config (pub key only, browser-safe).
window.RUNMOA = {
  "useApi": true,
  "siteHost": "doctoryang.runmoa.com",
  "storefrontKey": "moa_pub_5Gpb1bb-rPFdD0hR6s7sNcMNI-JUVDpj6MygfxswXZN3Aq6v98pXu2e5DKDQhvWs",
  "limit": 48
};
